services:
  mysql:
    restart: always
    image: mysql:8
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./conf.d:/etc/mysql/conf.d
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306